import { edge } from "./ModelEdge";

export const initialEdges = [
  // simulator chain
  edge("e-dr-rt",   "DecisionResult",  "RuleTrace",        "trace[]",         "#a52a20"),
  edge("e-rt-cr",   "RuleTrace",       "ConditionResult",  "conditions[]",    "#a52a20"),
  edge("e-cr-or",   "ConditionResult", "OperandResult",    "operands[]",      "#a52a20"),
  edge("e-dr-prr",  "DecisionResult",  "PolicyRuleResource", "matched_rule",  "#a52a20"),
  edge("e-snap-prr", "Snapshot", "PolicyRuleResource",         "AccessPolicies[]",  "#534ab7"),
  edge("e-snap-seg", "Snapshot", "ApplicationSegmentResource", "Segments[]",        "#534ab7"),
  edge("e-snap-sg",  "Snapshot", "SegmentGroup",               "SegmentGroups[]",   "#534ab7"),
  edge("e-snap-srv", "Snapshot", "ServerGroup",                "ServerGroups[]",    "#534ab7"),
  edge("e-snap-sc",  "Snapshot", "ScimGroup",                  "ScimGroups[]",      "#534ab7"),
  edge("e-snap-tn",  "Snapshot", "TrustedNetwork",             "TrustedNetworks[]", "#534ab7"),
  edge("e-snap-idp", "Snapshot", "IdpController",              "IdpControllers[]",  "#534ab7"),
  edge("e-idx-or",  "Index", "OrphanReport",  "OrphanSegments",     "#534ab7"),
  edge("e-idx-ovr", "Index", "OverlapReport", "OverlappingDomains", "#534ab7"),
  edge("e-prr-cond",  "PolicyRuleResource",           "PolicyRuleResourceConditions", "conditions[]",          "#185fa5"),
  edge("e-cond-opnd", "PolicyRuleResourceConditions", "PolicyRuleResourceOperands",   "operands[]",            "#185fa5"),
  edge("e-opnd-lhs",  "PolicyRuleResourceOperands",   "OperandsLHSRHS",               "entryValues[]",         "#185fa5"),
  edge("e-prr-pc",    "PolicyRuleResource",           "PrivilegedCapabilities",        "privilegedCapabilities","#185fa5"),
  edge("e-prr-cred",  "PolicyRuleResource",           "Credential",                   "credential",            "#185fa5"),
  edge("e-prr-srv",   "PolicyRuleResource",           "ServerGroup",                  "appServerGroups[]",     "#185fa5"),
  edge("e-prr-acg",   "PolicyRuleResource",           "AppConnectorGroup",            "appConnectorGroups[]",  "#185fa5"),
  edge("e-seg-sg",   "ApplicationSegmentResource", "SegmentGroup",             "segmentGroupId",           "#1d9e75"),
  edge("e-seg-srvg", "ApplicationSegmentResource", "ServerGroup",              "serverGroups[]",           "#1d9e75"),
  edge("e-seg-smd",  "ApplicationSegmentResource", "SharedMicrotenantDetails", "sharedMicrotenantDetails", "#1d9e75"),
  edge("e-seg-np",   "ApplicationSegmentResource", "NetworkPorts",             "tcpPortRange[]",           "#1d9e75"),
  edge("e-seg-er",   "ApplicationSegmentResource", "ZPNERID",                  "zpnErId",                  "#1d9e75"),
  edge("e-sg-seg",   "SegmentGroup",              "ApplicationSegmentResource","applications[]",           "#1d9e75"),
  edge("e-srv-acg", "ServerGroup",       "AppConnectorGroup", "appConnectorGroups[]", "#ba7517"),
  edge("e-srv-as",  "ServerGroup",       "ApplicationServer", "servers[]",            "#ba7517"),
  edge("e-srv-ext", "ServerGroup",       "ExtranetDTO",       "extranetDTO",          "#ba7517"),
  edge("e-acg-ac",  "AppConnectorGroup", "AppConnector",      "connectors[]",         "#ba7517"),
  edge("e-opnd-scimg", "PolicyRuleResourceOperands", "ScimGroup",          "rhs=groupId (SCIM_GROUP)",   "#888"),
  edge("e-opnd-scima", "PolicyRuleResourceOperands", "ScimAttributeHeader","lhs=attrId (SCIM)",          "#888"),
  edge("e-opnd-pp",    "PolicyRuleResourceOperands", "PostureProfile",     "rhs=postureUdid (POSTURE)",  "#888"),
  edge("e-opnd-tn",    "PolicyRuleResourceOperands", "TrustedNetwork",     "rhs=networkId (TRUSTED_NW)", "#888"),
  edge("e-sim-db", "DecisionResult", "SimulationRun", "persisted as JSON", "#444"),
];