// Code generated by apigen; DO NOT EDIT.
/* eslint-disable */

import type { analysis, appconnectorcontroller, appconnectorgroup, applicationsegment, bacertificate, idpcontroller, index, logging, policysetcontrollerv2, postureprofile, scimattributeheader, scimgroup, segmentgroup, server, servergroup, simulator, storage, trustednetwork } from './models.gen';

async function _fetch<T>(url: string, opts?: RequestInit): Promise<T> {
  const r = await fetch(url, opts);
  if (!r.ok) {
    const text = await r.text();
    throw new Error(text || r.statusText);
  }
  if (r.status === 204) return undefined as T;
  return (await r.json()) as T;
}

export function Refresh(): Promise<void> {
  return _fetch('/api/v1/refresh', { method: 'POST' });
}

export function GetIndex(): Promise<index.Index> {
  return _fetch('/api/v1/index');
}

export function Search(term: string): Promise<index.SearchResult[]> {
  return _fetch(`/api/v1/search?q=${encodeURIComponent(String(term))}`);
}

export function PoliciesForSegment(segmentID: string): Promise<index.PolicyCoverage[]> {
  return _fetch(`/api/v1/segment/${segmentID}/policies`);
}

export function WhoCanReach(hostname: string): Promise<index.ReachabilityResult> {
  return _fetch(`/api/v1/reachability?q=${encodeURIComponent(String(hostname))}`);
}

export function GetOrphans(): Promise<index.OrphanReport[]> {
  return _fetch('/api/v1/reports/orphans');
}

export function GetOverlaps(): Promise<index.OverlapReport[]> {
  return _fetch('/api/v1/reports/overlaps');
}

export function GetAbout(): Promise<server.About> {
  return _fetch('/api/v1/about');
}

export function GetLibraries(): Promise<server.Libraries> {
  return _fetch('/api/v1/libraries');
}

export function RunSimulation(simCtx: simulator.SimContext): Promise<simulator.DecisionResult> {
  return _fetch('/api/v1/simulation/run', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(simCtx),
  });
}

export function CompareSimulation(req: server.CompareRequest): Promise<server.CompareResult> {
  return _fetch('/api/v1/simulation/compare', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(req),
  });
}

export function GetMe(): Promise<server.Identity> {
  return _fetch('/api/v1/me');
}

export function PostTelemetry(batch: logging.TelemetryBatch): Promise<void> {
  return _fetch('/api/v1/telemetry', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(batch),
  });
}

export function ListSimulationRuns(limit: number, offset: number): Promise<storage.SimulationRun[]> {
  return _fetch(`/api/v1/simulation?limit=${encodeURIComponent(String(limit))}&offset=${encodeURIComponent(String(offset))}`);
}

export function GetSimulationRun(id: number): Promise<storage.SimulationRun> {
  return _fetch(`/api/v1/simulation/${id}`);
}

export function DeleteSimulationRun(id: number): Promise<void> {
  return _fetch(`/api/v1/simulation/${id}`, { method: 'DELETE' });
}

export function CountSimulationRuns(): Promise<number> {
  return _fetch('/api/v1/simulation/count');
}

export function GetFlowGraph(data: analysis.GraphQueryBody): Promise<analysis.FlowGraph> {
  return _fetch('/api/v1/graph', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });
}

export function GetClientTypes(): Promise<string[]> {
  return _fetch('/api/v1/zpa/client-types');
}

export function GetPlatforms(): Promise<string[]> {
  return _fetch('/api/v1/zpa/platforms');
}

export function GetSegments(): Promise<applicationsegment.ApplicationSegmentResource[]> {
  return _fetch('/api/v1/zpa/segments');
}

export function GetSegmentGroups(): Promise<segmentgroup.SegmentGroup[]> {
  return _fetch('/api/v1/zpa/segment-groups');
}

export function GetAppConnectors(): Promise<appconnectorcontroller.AppConnector[]> {
  return _fetch('/api/v1/zpa/app-connectors');
}

export function GetAppConnectorGroups(): Promise<appconnectorgroup.AppConnectorGroup[]> {
  return _fetch('/api/v1/zpa/app-connector-groups');
}

export function GetAccessPolicies(): Promise<policysetcontrollerv2.PolicyRuleResource[]> {
  return _fetch('/api/v1/zpa/access-policies');
}

export function GetScimGroups(): Promise<scimgroup.ScimGroup[]> {
  return _fetch('/api/v1/zpa/scim-groups');
}

export function GetScimAttributeHeaders(): Promise<scimattributeheader.ScimAttributeHeader[]> {
  return _fetch('/api/v1/zpa/scim-attribute-headers');
}

export function GetScimAttributeValues(idpID: string, headerID: string): Promise<string[]> {
  return _fetch(`/api/v1/zpa/scim-attribute-values?idpID=${encodeURIComponent(String(idpID))}&headerID=${encodeURIComponent(String(headerID))}`);
}

export function GetServerGroups(): Promise<servergroup.ServerGroup[]> {
  return _fetch('/api/v1/zpa/server-groups');
}

export function GetIdpControllers(): Promise<idpcontroller.IdpController[]> {
  return _fetch('/api/v1/zpa/idp-controllers');
}

export function GetTrustedNetworks(): Promise<trustednetwork.TrustedNetwork[]> {
  return _fetch('/api/v1/zpa/trusted-networks');
}

export function GetPostureProfiles(): Promise<postureprofile.PostureProfile[]> {
  return _fetch('/api/v1/zpa/posture-profiles');
}

export function GetCertificates(): Promise<bacertificate.BaCertificate[]> {
  return _fetch('/api/v1/zpa/certificates');
}

export function GetBlastRadius(targetID: string, targetType: string): Promise<analysis.BlastRadiusReport> {
  return _fetch(`/api/v1/analytics/blast-radius?targetId=${encodeURIComponent(String(targetID))}&targetType=${encodeURIComponent(String(targetType))}`);
}

export function GetPolicyShadows(): Promise<analysis.PolicyShadowReport[]> {
  return _fetch('/api/v1/analytics/policy-shadows');
}

export function GetOrphanClusters(): Promise<analysis.OrphanCluster[]> {
  return _fetch('/api/v1/analytics/orphan-clusters');
}

export function GetDomainOverlaps(): Promise<analysis.DomainOverlapDetail[]> {
  return _fetch('/api/v1/analytics/domain-overlaps');
}

export function GetConnectorLoad(): Promise<analysis.ConnectorLoadEntry[]> {
  return _fetch('/api/v1/analytics/connector-load');
}

export function GetScimReach(): Promise<analysis.ScimReachEntry[]> {
  return _fetch('/api/v1/analytics/scim-reach');
}

export function GetRoutes(): Promise<analysis.RouteMatrix> {
  return _fetch('/api/v1/routes');
}

