// Code generated by apigen; DO NOT EDIT.
/* eslint-disable */

export namespace analysis {
	export class BlastRadiusReport {
		targetId: string;
		targetName: string;
		targetType: string;
		policies: analysis.NamedRef[];
		scimGroups: analysis.NamedRef[];
		segments: analysis.NamedRef[];

		static createFrom(source: any = {}) {
			return new BlastRadiusReport(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["targetId"] = source["targetId"];
			this["targetName"] = source["targetName"];
			this["targetType"] = source["targetType"];
			this["policies"] = source["policies"];
			this["scimGroups"] = source["scimGroups"];
			this["segments"] = source["segments"];
		}
	}
	export class ConnectorLoadEntry {
		connectorGroupId: string;
		connectorGroupName: string;
		policyCount: number;
		segmentGroupCount: number;
		segmentCount: number;
		scimGroupCount: number;

		static createFrom(source: any = {}) {
			return new ConnectorLoadEntry(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["connectorGroupId"] = source["connectorGroupId"];
			this["connectorGroupName"] = source["connectorGroupName"];
			this["policyCount"] = source["policyCount"];
			this["segmentGroupCount"] = source["segmentGroupCount"];
			this["segmentCount"] = source["segmentCount"];
			this["scimGroupCount"] = source["scimGroupCount"];
		}
	}
	export class DomainOverlapDetail {
		domain: string;
		segments: analysis.DomainSegmentDetail[];
		hasConflict: boolean;

		static createFrom(source: any = {}) {
			return new DomainOverlapDetail(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["domain"] = source["domain"];
			this["segments"] = source["segments"];
			this["hasConflict"] = source["hasConflict"];
		}
	}
	export class DomainSegmentDetail {
		id: string;
		name: string;
		policies: analysis.NamedRef[];

		static createFrom(source: any = {}) {
			return new DomainSegmentDetail(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["name"] = source["name"];
			this["policies"] = source["policies"];
		}
	}
	export type FlowColumn = number;
	export class FlowEdge {
		id: string;
		source: string;
		target: string;
		type: string;

		static createFrom(source: any = {}) {
			return new FlowEdge(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["source"] = source["source"];
			this["target"] = source["target"];
			this["type"] = source["type"];
		}
	}
	export class FlowFilters {
		scimGroupIds: Record<string, boolean>;
		policyIds: Record<string, boolean>;
		connectorGroupIds: Record<string, boolean>;
		segmentGroupIds: Record<string, boolean>;

		static createFrom(source: any = {}) {
			return new FlowFilters(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["scimGroupIds"] = source["scimGroupIds"];
			this["policyIds"] = source["policyIds"];
			this["connectorGroupIds"] = source["connectorGroupIds"];
			this["segmentGroupIds"] = source["segmentGroupIds"];
		}
	}
	export class FlowGraph {
		nodes: analysis.FlowNode[];
		edges: analysis.FlowEdge[];

		static createFrom(source: any = {}) {
			return new FlowGraph(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["nodes"] = source["nodes"];
			this["edges"] = source["edges"];
		}
	}
	export class FlowNode {
		id: string;
		type: string;
		position: analysis.RFPosition;
		data: analysis.FlowNodeData;
		width: number;

		static createFrom(source: any = {}) {
			return new FlowNode(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["type"] = source["type"];
			this["position"] = source["position"];
			this["data"] = source["data"];
			this["width"] = source["width"];
		}
	}
	export class FlowNodeData {
		column: analysis.FlowColumn;
		label: string;
		subtitle?: string;

		static createFrom(source: any = {}) {
			return new FlowNodeData(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["column"] = source["column"];
			this["label"] = source["label"];
			this["subtitle"] = source["subtitle"];
		}
	}
	export class GraphQueryBody {
		filters?: analysis.FlowFilters;
		visible_cols?: Record<string, boolean>;
		expanded_groups?: Record<string, boolean>;

		static createFrom(source: any = {}) {
			return new GraphQueryBody(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["filters"] = source["filters"];
			this["visible_cols"] = source["visible_cols"];
			this["expanded_groups"] = source["expanded_groups"];
		}
	}
	export class NamedRef {
		id: string;
		name: string;

		static createFrom(source: any = {}) {
			return new NamedRef(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["name"] = source["name"];
		}
	}
	export class OrphanCluster {
		segmentGroupId: string;
		segmentGroupName: string;
		fullyOrphaned: boolean;
		orphanSegments: analysis.NamedRef[];
		connectorGroups: analysis.NamedRef[];

		static createFrom(source: any = {}) {
			return new OrphanCluster(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["segmentGroupId"] = source["segmentGroupId"];
			this["segmentGroupName"] = source["segmentGroupName"];
			this["fullyOrphaned"] = source["fullyOrphaned"];
			this["orphanSegments"] = source["orphanSegments"];
			this["connectorGroups"] = source["connectorGroups"];
		}
	}
	export class PolicyShadowReport {
		policyA: analysis.PolicySummary;
		policyB: analysis.PolicySummary;
		sharedScimGroups: analysis.NamedRef[];
		sharedSegments: analysis.NamedRef[];
		verdict: string;

		static createFrom(source: any = {}) {
			return new PolicyShadowReport(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["policyA"] = source["policyA"];
			this["policyB"] = source["policyB"];
			this["sharedScimGroups"] = source["sharedScimGroups"];
			this["sharedSegments"] = source["sharedSegments"];
			this["verdict"] = source["verdict"];
		}
	}
	export class PolicySummary {
		id: string;
		name: string;
		action: string;
		priority: number;

		static createFrom(source: any = {}) {
			return new PolicySummary(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["name"] = source["name"];
			this["action"] = source["action"];
			this["priority"] = source["priority"];
		}
	}
	export class RFPosition {
		x: number;
		y: number;

		static createFrom(source: any = {}) {
			return new RFPosition(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["x"] = source["x"];
			this["y"] = source["y"];
		}
	}
	export class Route {
		scimGroup: analysis.RouteEntry;
		policy: analysis.RouteEntry;
		connectorGroup: analysis.RouteEntry;
		segmentGroup: analysis.RouteEntry;
		segment: analysis.RouteEntry;

		static createFrom(source: any = {}) {
			return new Route(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["scimGroup"] = source["scimGroup"];
			this["policy"] = source["policy"];
			this["connectorGroup"] = source["connectorGroup"];
			this["segmentGroup"] = source["segmentGroup"];
			this["segment"] = source["segment"];
		}
	}
	export class RouteEntry {
		id: string;
		name: string;

		static createFrom(source: any = {}) {
			return new RouteEntry(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["name"] = source["name"];
		}
	}
	export class RouteMatrix {
		routes: analysis.Route[];

		static createFrom(source: any = {}) {
			return new RouteMatrix(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["routes"] = source["routes"];
		}
	}
	export class ScimReachEntry {
		scimGroupId: string;
		scimGroupName: string;
		policyCount: number;
		segmentGroupCount: number;
		segmentCount: number;

		static createFrom(source: any = {}) {
			return new ScimReachEntry(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["scimGroupId"] = source["scimGroupId"];
			this["scimGroupName"] = source["scimGroupName"];
			this["policyCount"] = source["policyCount"];
			this["segmentGroupCount"] = source["segmentGroupCount"];
			this["segmentCount"] = source["segmentCount"];
		}
	}
}

export namespace appconnectorcontroller {
	export class AppConnector {
		applicationStartTime?: string;
		appConnectorGroupId?: string;
		appConnectorGroupName?: string;
		assistantVersion?: appconnectorcontroller.AssistantVersion;
		controlChannelStatus?: string;
		creationTime?: string;
		ctrlBrokerName?: string;
		currentVersion?: string;
		description?: string;
		enabled?: boolean;
		expectedUpgradeTime?: string;
		expectedVersion?: string;
		fingerprint?: string;
		id?: string;
		ipAcl?: string;
		issuedCertId?: string;
		lastBrokerConnectTime?: string;
		lastBrokerConnectTimeDuration?: string;
		lastBrokerDisconnectTime?: string;
		lastBrokerDisconnectTimeDuration?: string;
		lastUpgradeTime?: string;
		latitude?: string;
		location?: string;
		longitude?: string;
		modifiedBy?: string;
		modifiedTime?: string;
		name?: string;
		provisioningKeyId: string;
		provisioningKeyName: string;
		platform?: string;
		platformDetail?: string;
		previousVersion?: string;
		privateIp?: string;
		publicIp?: string;
		runtimeOS?: string;
		sargeVersion?: string;
		enrollmentCert?: Record<string, any>;
		upgradeAttempt?: string;
		upgradeStatus?: string;
		microtenantId?: string;
		microtenantName?: string;
		readOnly?: boolean;
		restrictionType?: string;
		zscalerManaged?: boolean;
		zpnSubModuleUpgradeList?: common.ZPNSubModuleUpgrade[];

		static createFrom(source: any = {}) {
			return new AppConnector(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["applicationStartTime"] = source["applicationStartTime"];
			this["appConnectorGroupId"] = source["appConnectorGroupId"];
			this["appConnectorGroupName"] = source["appConnectorGroupName"];
			this["assistantVersion"] = source["assistantVersion"];
			this["controlChannelStatus"] = source["controlChannelStatus"];
			this["creationTime"] = source["creationTime"];
			this["ctrlBrokerName"] = source["ctrlBrokerName"];
			this["currentVersion"] = source["currentVersion"];
			this["description"] = source["description"];
			this["enabled"] = source["enabled"];
			this["expectedUpgradeTime"] = source["expectedUpgradeTime"];
			this["expectedVersion"] = source["expectedVersion"];
			this["fingerprint"] = source["fingerprint"];
			this["id"] = source["id"];
			this["ipAcl"] = source["ipAcl"];
			this["issuedCertId"] = source["issuedCertId"];
			this["lastBrokerConnectTime"] = source["lastBrokerConnectTime"];
			this["lastBrokerConnectTimeDuration"] = source["lastBrokerConnectTimeDuration"];
			this["lastBrokerDisconnectTime"] = source["lastBrokerDisconnectTime"];
			this["lastBrokerDisconnectTimeDuration"] = source["lastBrokerDisconnectTimeDuration"];
			this["lastUpgradeTime"] = source["lastUpgradeTime"];
			this["latitude"] = source["latitude"];
			this["location"] = source["location"];
			this["longitude"] = source["longitude"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["name"] = source["name"];
			this["provisioningKeyId"] = source["provisioningKeyId"];
			this["provisioningKeyName"] = source["provisioningKeyName"];
			this["platform"] = source["platform"];
			this["platformDetail"] = source["platformDetail"];
			this["previousVersion"] = source["previousVersion"];
			this["privateIp"] = source["privateIp"];
			this["publicIp"] = source["publicIp"];
			this["runtimeOS"] = source["runtimeOS"];
			this["sargeVersion"] = source["sargeVersion"];
			this["enrollmentCert"] = source["enrollmentCert"];
			this["upgradeAttempt"] = source["upgradeAttempt"];
			this["upgradeStatus"] = source["upgradeStatus"];
			this["microtenantId"] = source["microtenantId"];
			this["microtenantName"] = source["microtenantName"];
			this["readOnly"] = source["readOnly"];
			this["restrictionType"] = source["restrictionType"];
			this["zscalerManaged"] = source["zscalerManaged"];
			this["zpnSubModuleUpgradeList"] = source["zpnSubModuleUpgradeList"];
		}
	}
	export class AssistantVersion {
		id?: string;
		applicationStartTime?: string;
		appConnectorGroupId?: string;
		brokerId?: string;
		creationTime?: string;
		ctrlChannelStatus?: string;
		currentVersion?: string;
		disableAutoUpdate?: boolean;
		expectedVersion?: string;
		lastBrokerConnectTime?: string;
		lastBrokerDisconnectTime?: string;
		lastUpgradedTime?: string;
		loneWarrior?: boolean;
		modifiedBy?: string;
		modifiedTime?: string;
		latitude?: string;
		longitude?: string;
		mtunnelId?: string;
		platform?: string;
		platformDetail?: string;
		previousVersion?: string;
		privateIp?: string;
		publicIp?: string;
		restartTimeInSec?: string;
		runtimeOS?: string;
		sargeVersion?: string;
		systemStartTime?: string;
		upgradeAttempt?: string;
		upgradeStatus?: string;
		upgradeNowOnce?: boolean;

		static createFrom(source: any = {}) {
			return new AssistantVersion(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["applicationStartTime"] = source["applicationStartTime"];
			this["appConnectorGroupId"] = source["appConnectorGroupId"];
			this["brokerId"] = source["brokerId"];
			this["creationTime"] = source["creationTime"];
			this["ctrlChannelStatus"] = source["ctrlChannelStatus"];
			this["currentVersion"] = source["currentVersion"];
			this["disableAutoUpdate"] = source["disableAutoUpdate"];
			this["expectedVersion"] = source["expectedVersion"];
			this["lastBrokerConnectTime"] = source["lastBrokerConnectTime"];
			this["lastBrokerDisconnectTime"] = source["lastBrokerDisconnectTime"];
			this["lastUpgradedTime"] = source["lastUpgradedTime"];
			this["loneWarrior"] = source["loneWarrior"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["latitude"] = source["latitude"];
			this["longitude"] = source["longitude"];
			this["mtunnelId"] = source["mtunnelId"];
			this["platform"] = source["platform"];
			this["platformDetail"] = source["platformDetail"];
			this["previousVersion"] = source["previousVersion"];
			this["privateIp"] = source["privateIp"];
			this["publicIp"] = source["publicIp"];
			this["restartTimeInSec"] = source["restartTimeInSec"];
			this["runtimeOS"] = source["runtimeOS"];
			this["sargeVersion"] = source["sargeVersion"];
			this["systemStartTime"] = source["systemStartTime"];
			this["upgradeAttempt"] = source["upgradeAttempt"];
			this["upgradeStatus"] = source["upgradeStatus"];
			this["upgradeNowOnce"] = source["upgradeNowOnce"];
		}
	}
}

export namespace appconnectorgroup {
	export class AppConnectorGroup {
		id?: string;
		name?: string;
		description?: string;
		enabled: boolean;
		cityCountry: string;
		countryCode?: string;
		creationTime?: string;
		dnsQueryType?: string;
		connectorGroupType?: string;
		geoLocationId?: string;
		latitude?: string;
		location?: string;
		longitude?: string;
		modifiedBy?: string;
		modifiedTime?: string;
		overrideVersionProfile: boolean;
		praEnabled: boolean;
		wafDisabled: boolean;
		upgradeDay?: string;
		upgradeTimeInSecs?: string;
		versionProfileId?: string;
		versionProfileName?: string;
		versionProfileVisibilityScope?: string;
		tcpQuickAckApp: boolean;
		tcpQuickAckAssistant: boolean;
		useInDrMode: boolean;
		tcpQuickAckReadAssistant: boolean;
		lssAppConnectorGroup: boolean;
		microtenantId?: string;
		microtenantName?: string;
		siteId?: string;
		siteName?: string;
		readOnly?: boolean;
		restrictionType?: string;
		zscalerManaged?: boolean;
		dcHostingInfo: string;
		nameWithoutTrim?: string;
		serverGroups?: appconnectorgroup.AppServerGroup[];
		connectors?: appconnectorcontroller.AppConnector[];
		npAssistantGroup?: appconnectorgroup.NPAssistantGroup;
		enrollmentCertId?: string;

		static createFrom(source: any = {}) {
			return new AppConnectorGroup(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["name"] = source["name"];
			this["description"] = source["description"];
			this["enabled"] = source["enabled"];
			this["cityCountry"] = source["cityCountry"];
			this["countryCode"] = source["countryCode"];
			this["creationTime"] = source["creationTime"];
			this["dnsQueryType"] = source["dnsQueryType"];
			this["connectorGroupType"] = source["connectorGroupType"];
			this["geoLocationId"] = source["geoLocationId"];
			this["latitude"] = source["latitude"];
			this["location"] = source["location"];
			this["longitude"] = source["longitude"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["overrideVersionProfile"] = source["overrideVersionProfile"];
			this["praEnabled"] = source["praEnabled"];
			this["wafDisabled"] = source["wafDisabled"];
			this["upgradeDay"] = source["upgradeDay"];
			this["upgradeTimeInSecs"] = source["upgradeTimeInSecs"];
			this["versionProfileId"] = source["versionProfileId"];
			this["versionProfileName"] = source["versionProfileName"];
			this["versionProfileVisibilityScope"] = source["versionProfileVisibilityScope"];
			this["tcpQuickAckApp"] = source["tcpQuickAckApp"];
			this["tcpQuickAckAssistant"] = source["tcpQuickAckAssistant"];
			this["useInDrMode"] = source["useInDrMode"];
			this["tcpQuickAckReadAssistant"] = source["tcpQuickAckReadAssistant"];
			this["lssAppConnectorGroup"] = source["lssAppConnectorGroup"];
			this["microtenantId"] = source["microtenantId"];
			this["microtenantName"] = source["microtenantName"];
			this["siteId"] = source["siteId"];
			this["siteName"] = source["siteName"];
			this["readOnly"] = source["readOnly"];
			this["restrictionType"] = source["restrictionType"];
			this["zscalerManaged"] = source["zscalerManaged"];
			this["dcHostingInfo"] = source["dcHostingInfo"];
			this["nameWithoutTrim"] = source["nameWithoutTrim"];
			this["serverGroups"] = source["serverGroups"];
			this["connectors"] = source["connectors"];
			this["npAssistantGroup"] = source["npAssistantGroup"];
			this["enrollmentCertId"] = source["enrollmentCertId"];
		}
	}
	export class AppServerGroup {
		configSpace?: string;
		creationTime?: string;
		description?: string;
		enabled?: boolean;
		id?: string;
		dynamicDiscovery?: boolean;
		modifiedBy?: string;
		modifiedTime?: string;
		name?: string;

		static createFrom(source: any = {}) {
			return new AppServerGroup(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["configSpace"] = source["configSpace"];
			this["creationTime"] = source["creationTime"];
			this["description"] = source["description"];
			this["enabled"] = source["enabled"];
			this["id"] = source["id"];
			this["dynamicDiscovery"] = source["dynamicDiscovery"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["name"] = source["name"];
		}
	}
	export class LanSubnet {
		id?: string;
		name?: string;
		description?: string;
		appConnectorGroupId?: string;
		creationTime?: string;
		modifiedBy?: string;
		modifiedTime?: string;
		npDnsNsRecord?: appconnectorgroup.NPDnsNsRecord;
		oldAuditString?: string;
		subnet?: string;
		npserverips?: string[];
		fqdns?: string[];

		static createFrom(source: any = {}) {
			return new LanSubnet(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["name"] = source["name"];
			this["description"] = source["description"];
			this["appConnectorGroupId"] = source["appConnectorGroupId"];
			this["creationTime"] = source["creationTime"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["npDnsNsRecord"] = source["npDnsNsRecord"];
			this["oldAuditString"] = source["oldAuditString"];
			this["subnet"] = source["subnet"];
			this["npserverips"] = source["npserverips"];
			this["fqdns"] = source["fqdns"];
		}
	}
	export class NPAssistantGroup {
		id?: string;
		appConnectorGroupId?: string;
		creationTime?: string;
		modifiedBy?: string;
		modifiedTime?: string;
		mtu?: string;
		lanSubnets?: appconnectorgroup.LanSubnet[];

		static createFrom(source: any = {}) {
			return new NPAssistantGroup(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["appConnectorGroupId"] = source["appConnectorGroupId"];
			this["creationTime"] = source["creationTime"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["mtu"] = source["mtu"];
			this["lanSubnets"] = source["lanSubnets"];
		}
	}
	export class NPDnsNsRecord {
		creationTime?: string;
		fqdn?: string[];
		id?: string;
		modifiedBy?: string;
		modifiedTime?: string;
		name?: string;
		nameserverIps?: string[];

		static createFrom(source: any = {}) {
			return new NPDnsNsRecord(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["creationTime"] = source["creationTime"];
			this["fqdn"] = source["fqdn"];
			this["id"] = source["id"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["name"] = source["name"];
			this["nameserverIps"] = source["nameserverIps"];
		}
	}
}

export namespace applicationsegment {
	export class ApplicationSegmentResource {
		id?: string;
		domainNames?: string[];
		name?: string;
		description?: string;
		enabled: boolean;
		extranetEnabled: boolean;
		apiProtectionEnabled: boolean;
		autoAppProtectEnabled: boolean;
		adpEnabled: boolean;
		passiveHealthEnabled: boolean;
		doubleEncrypt: boolean;
		configSpace?: string;
		applications?: string;
		bypassType?: string;
		bypassOnReauth?: boolean;
		healthCheckType?: string;
		isCnameEnabled: boolean;
		ipAnchored: boolean;
		fqdnDnsCheck: boolean;
		healthReporting?: string;
		selectConnectorCloseToApp: boolean;
		icmpAccessType?: string;
		appRecommendationId?: string;
		segmentGroupId: string;
		segmentGroupName?: string;
		creationTime?: string;
		modifiedBy?: string;
		modifiedTime?: string;
		tcpKeepAlive?: string;
		isIncompleteDRConfig: boolean;
		useInDrMode: boolean;
		inspectTrafficWithZia: boolean;
		weightedLoadBalancing: boolean;
		microtenantId?: string;
		microtenantName?: string;
		matchStyle?: string;
		readOnly?: boolean;
		restrictionType?: string;
		zscalerManaged?: boolean;
		tcpPortRanges: string[];
		udpPortRanges: string[];
		tcpPortRange?: common.NetworkPorts[];
		udpPortRange?: common.NetworkPorts[];
		serverGroups: servergroup.ServerGroup[];
		defaultIdleTimeout?: string;
		defaultMaxAge?: string;
		clientlessApps?: applicationsegmentbrowseraccess.ClientlessApps[];
		shareToMicrotenants: string[];
		sharedMicrotenantDetails?: applicationsegment.SharedMicrotenantDetails;
		zpnErId: common.ZPNERID;
		tags?: applicationsegment.Tag[];
		policyStyle?: string;

		static createFrom(source: any = {}) {
			return new ApplicationSegmentResource(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["domainNames"] = source["domainNames"];
			this["name"] = source["name"];
			this["description"] = source["description"];
			this["enabled"] = source["enabled"];
			this["extranetEnabled"] = source["extranetEnabled"];
			this["apiProtectionEnabled"] = source["apiProtectionEnabled"];
			this["autoAppProtectEnabled"] = source["autoAppProtectEnabled"];
			this["adpEnabled"] = source["adpEnabled"];
			this["passiveHealthEnabled"] = source["passiveHealthEnabled"];
			this["doubleEncrypt"] = source["doubleEncrypt"];
			this["configSpace"] = source["configSpace"];
			this["applications"] = source["applications"];
			this["bypassType"] = source["bypassType"];
			this["bypassOnReauth"] = source["bypassOnReauth"];
			this["healthCheckType"] = source["healthCheckType"];
			this["isCnameEnabled"] = source["isCnameEnabled"];
			this["ipAnchored"] = source["ipAnchored"];
			this["fqdnDnsCheck"] = source["fqdnDnsCheck"];
			this["healthReporting"] = source["healthReporting"];
			this["selectConnectorCloseToApp"] = source["selectConnectorCloseToApp"];
			this["icmpAccessType"] = source["icmpAccessType"];
			this["appRecommendationId"] = source["appRecommendationId"];
			this["segmentGroupId"] = source["segmentGroupId"];
			this["segmentGroupName"] = source["segmentGroupName"];
			this["creationTime"] = source["creationTime"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["tcpKeepAlive"] = source["tcpKeepAlive"];
			this["isIncompleteDRConfig"] = source["isIncompleteDRConfig"];
			this["useInDrMode"] = source["useInDrMode"];
			this["inspectTrafficWithZia"] = source["inspectTrafficWithZia"];
			this["weightedLoadBalancing"] = source["weightedLoadBalancing"];
			this["microtenantId"] = source["microtenantId"];
			this["microtenantName"] = source["microtenantName"];
			this["matchStyle"] = source["matchStyle"];
			this["readOnly"] = source["readOnly"];
			this["restrictionType"] = source["restrictionType"];
			this["zscalerManaged"] = source["zscalerManaged"];
			this["tcpPortRanges"] = source["tcpPortRanges"];
			this["udpPortRanges"] = source["udpPortRanges"];
			this["tcpPortRange"] = source["tcpPortRange"];
			this["udpPortRange"] = source["udpPortRange"];
			this["serverGroups"] = source["serverGroups"];
			this["defaultIdleTimeout"] = source["defaultIdleTimeout"];
			this["defaultMaxAge"] = source["defaultMaxAge"];
			this["clientlessApps"] = source["clientlessApps"];
			this["shareToMicrotenants"] = source["shareToMicrotenants"];
			this["sharedMicrotenantDetails"] = source["sharedMicrotenantDetails"];
			this["zpnErId"] = source["zpnErId"];
			this["tags"] = source["tags"];
			this["policyStyle"] = source["policyStyle"];
		}
	}
	export class SharedFromMicrotenant {
		id?: string;
		name?: string;

		static createFrom(source: any = {}) {
			return new SharedFromMicrotenant(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["name"] = source["name"];
		}
	}
	export class SharedMicrotenantDetails {
		sharedFromMicrotenant?: applicationsegment.SharedFromMicrotenant;
		sharedToMicrotenants?: applicationsegment.SharedToMicrotenant[];

		static createFrom(source: any = {}) {
			return new SharedMicrotenantDetails(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["sharedFromMicrotenant"] = source["sharedFromMicrotenant"];
			this["sharedToMicrotenants"] = source["sharedToMicrotenants"];
		}
	}
	export class SharedToMicrotenant {
		id?: string;
		name?: string;

		static createFrom(source: any = {}) {
			return new SharedToMicrotenant(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["name"] = source["name"];
		}
	}
	export class Tag {
		namespace?: common.CommonSummary;
		tagKey?: common.CommonSummary;
		tagValue?: common.CommonIDName;
		origin?: string;

		static createFrom(source: any = {}) {
			return new Tag(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["namespace"] = source["namespace"];
			this["tagKey"] = source["tagKey"];
			this["tagValue"] = source["tagValue"];
			this["origin"] = source["origin"];
		}
	}
}

export namespace applicationsegmentbrowseraccess {
	export class ClientlessApps {
		allowOptions: boolean;
		appId?: string;
		applicationPort?: string;
		applicationProtocol?: string;
		certificateId?: string;
		certificateName?: string;
		cname?: string;
		creationTime?: string;
		description?: string;
		domain?: string;
		enabled: boolean;
		hidden: boolean;
		id?: string;
		localDomain?: string;
		modifiedBy?: string;
		modifiedTime?: string;
		name?: string;
		path?: string;
		microtenantId?: string;
		microtenantName?: string;
		trustUntrustedCert: boolean;
		extDomain: string;
		extLabel: string;
		extDomainName: string;
		extId: string;

		static createFrom(source: any = {}) {
			return new ClientlessApps(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["allowOptions"] = source["allowOptions"];
			this["appId"] = source["appId"];
			this["applicationPort"] = source["applicationPort"];
			this["applicationProtocol"] = source["applicationProtocol"];
			this["certificateId"] = source["certificateId"];
			this["certificateName"] = source["certificateName"];
			this["cname"] = source["cname"];
			this["creationTime"] = source["creationTime"];
			this["description"] = source["description"];
			this["domain"] = source["domain"];
			this["enabled"] = source["enabled"];
			this["hidden"] = source["hidden"];
			this["id"] = source["id"];
			this["localDomain"] = source["localDomain"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["name"] = source["name"];
			this["path"] = source["path"];
			this["microtenantId"] = source["microtenantId"];
			this["microtenantName"] = source["microtenantName"];
			this["trustUntrustedCert"] = source["trustUntrustedCert"];
			this["extDomain"] = source["extDomain"];
			this["extLabel"] = source["extLabel"];
			this["extDomainName"] = source["extDomainName"];
			this["extId"] = source["extId"];
		}
	}
}

export namespace appservercontroller {
	export class ApplicationServer {
		address: string;
		appServerGroupIds: string[];
		configSpace?: string;
		creationTime: string;
		description: string;
		enabled: boolean;
		id?: string;
		modifiedBy: string;
		modifiedTime: string;
		name: string;
		microtenantId?: string;
		microtenantName?: string;

		static createFrom(source: any = {}) {
			return new ApplicationServer(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["address"] = source["address"];
			this["appServerGroupIds"] = source["appServerGroupIds"];
			this["configSpace"] = source["configSpace"];
			this["creationTime"] = source["creationTime"];
			this["description"] = source["description"];
			this["enabled"] = source["enabled"];
			this["id"] = source["id"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["name"] = source["name"];
			this["microtenantId"] = source["microtenantId"];
			this["microtenantName"] = source["microtenantName"];
		}
	}
}

export namespace bacertificate {
	export class BaCertificate {
		id?: string;
		name?: string;
		description?: string;
		cName?: string;
		certChain?: string;
		certBlob?: string;
		certificate?: string;
		publicKey?: string;
		creationTime?: string;
		issuedBy?: string;
		issuedTo?: string;
		modifiedBy?: string;
		modifiedTime?: string;
		san?: string[];
		serialNo?: string;
		status?: string;
		validFromInEpochSec?: string;
		validToInEpochSec?: string;
		microtenantId?: string;
		microtenantName?: string;

		static createFrom(source: any = {}) {
			return new BaCertificate(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["name"] = source["name"];
			this["description"] = source["description"];
			this["cName"] = source["cName"];
			this["certChain"] = source["certChain"];
			this["certBlob"] = source["certBlob"];
			this["certificate"] = source["certificate"];
			this["publicKey"] = source["publicKey"];
			this["creationTime"] = source["creationTime"];
			this["issuedBy"] = source["issuedBy"];
			this["issuedTo"] = source["issuedTo"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["san"] = source["san"];
			this["serialNo"] = source["serialNo"];
			this["status"] = source["status"];
			this["validFromInEpochSec"] = source["validFromInEpochSec"];
			this["validToInEpochSec"] = source["validToInEpochSec"];
			this["microtenantId"] = source["microtenantId"];
			this["microtenantName"] = source["microtenantName"];
		}
	}
}

export namespace common {
	export class CommonIDName {
		id?: string;
		name?: string;

		static createFrom(source: any = {}) {
			return new CommonIDName(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["name"] = source["name"];
		}
	}
	export class CommonSummary {
		id?: string;
		name?: string;
		enabled?: boolean;

		static createFrom(source: any = {}) {
			return new CommonSummary(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["name"] = source["name"];
			this["enabled"] = source["enabled"];
		}
	}
	export class ExtranetDTO {
		locationDTO?: common.LocationDTO[];
		locationGroupDTO?: common.LocationGroupDTO[];
		ziaErName?: string;
		zpnErId?: string;

		static createFrom(source: any = {}) {
			return new ExtranetDTO(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["locationDTO"] = source["locationDTO"];
			this["locationGroupDTO"] = source["locationGroupDTO"];
			this["ziaErName"] = source["ziaErName"];
			this["zpnErId"] = source["zpnErId"];
		}
	}
	export class LocationDTO {
		id?: string;
		name?: string;

		static createFrom(source: any = {}) {
			return new LocationDTO(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["name"] = source["name"];
		}
	}
	export class LocationGroupDTO {
		id?: string;
		name?: string;
		ziaLocations?: common.CommonSummary[];

		static createFrom(source: any = {}) {
			return new LocationGroupDTO(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["name"] = source["name"];
			this["ziaLocations"] = source["ziaLocations"];
		}
	}
	export class NetworkPorts {
		from?: string;
		to?: string;

		static createFrom(source: any = {}) {
			return new NetworkPorts(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["from"] = source["from"];
			this["to"] = source["to"];
		}
	}
	export class ZPNERID {
		id?: string;
		creationTime?: string;
		modifiedBy?: string;
		modifiedTime?: string;
		ziaCloud?: string;
		ziaErId?: string;
		ziaErName?: string;
		ziaModifiedTime?: string;
		ziaOrgId?: string;

		static createFrom(source: any = {}) {
			return new ZPNERID(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["creationTime"] = source["creationTime"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["ziaCloud"] = source["ziaCloud"];
			this["ziaErId"] = source["ziaErId"];
			this["ziaErName"] = source["ziaErName"];
			this["ziaModifiedTime"] = source["ziaModifiedTime"];
			this["ziaOrgId"] = source["ziaOrgId"];
		}
	}
	export class ZPNSubModuleUpgrade {
		id?: string;
		creationTime?: string;
		currentVersion?: string;
		entityGid?: string;
		entityType?: string;
		expectedVersion?: string;
		modifiedBy?: string;
		modifiedTime?: string;
		previousVersion?: string;
		role?: string;
		upgradeStatus?: string;
		upgradeTime?: string;

		static createFrom(source: any = {}) {
			return new ZPNSubModuleUpgrade(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["creationTime"] = source["creationTime"];
			this["currentVersion"] = source["currentVersion"];
			this["entityGid"] = source["entityGid"];
			this["entityType"] = source["entityType"];
			this["expectedVersion"] = source["expectedVersion"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["previousVersion"] = source["previousVersion"];
			this["role"] = source["role"];
			this["upgradeStatus"] = source["upgradeStatus"];
			this["upgradeTime"] = source["upgradeTime"];
		}
	}
}

export namespace idpcontroller {
	export class AdminMetadata {
		certificateUrl: string;
		spBaseUrl: string;
		spEntityId: string;
		spMetadataUrl: string;
		spPostUrl: string;

		static createFrom(source: any = {}) {
			return new AdminMetadata(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["certificateUrl"] = source["certificateUrl"];
			this["spBaseUrl"] = source["spBaseUrl"];
			this["spEntityId"] = source["spEntityId"];
			this["spMetadataUrl"] = source["spMetadataUrl"];
			this["spPostUrl"] = source["spPostUrl"];
		}
	}
	export class IdpController {
		adminSpSigningCertId?: string;
		autoProvision?: string;
		creationTime?: string;
		description?: string;
		disableSamlBasedPolicy: boolean;
		domainList?: string[];
		enableScimBasedPolicy: boolean;
		enableArbitraryAuthDomains: string;
		enabled: boolean;
		forceAuth: boolean;
		id?: string;
		idpEntityId?: string;
		loginHint?: boolean;
		loginNameAttribute?: string;
		loginUrl?: string;
		modifiedBy?: string;
		modifiedTime?: string;
		name?: string;
		reauthOnUserUpdate: boolean;
		redirectBinding: boolean;
		scimEnabled: boolean;
		scimServiceProviderEndpoint?: string;
		scimSharedSecretExists?: boolean;
		signSamlRequest?: string;
		ssoType?: string[];
		useCustomSPMetadata: boolean;
		userSpSigningCertId?: string;
		adminMetadata?: idpcontroller.AdminMetadata;
		userMetadata?: idpcontroller.UserMetadata;

		static createFrom(source: any = {}) {
			return new IdpController(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["adminSpSigningCertId"] = source["adminSpSigningCertId"];
			this["autoProvision"] = source["autoProvision"];
			this["creationTime"] = source["creationTime"];
			this["description"] = source["description"];
			this["disableSamlBasedPolicy"] = source["disableSamlBasedPolicy"];
			this["domainList"] = source["domainList"];
			this["enableScimBasedPolicy"] = source["enableScimBasedPolicy"];
			this["enableArbitraryAuthDomains"] = source["enableArbitraryAuthDomains"];
			this["enabled"] = source["enabled"];
			this["forceAuth"] = source["forceAuth"];
			this["id"] = source["id"];
			this["idpEntityId"] = source["idpEntityId"];
			this["loginHint"] = source["loginHint"];
			this["loginNameAttribute"] = source["loginNameAttribute"];
			this["loginUrl"] = source["loginUrl"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["name"] = source["name"];
			this["reauthOnUserUpdate"] = source["reauthOnUserUpdate"];
			this["redirectBinding"] = source["redirectBinding"];
			this["scimEnabled"] = source["scimEnabled"];
			this["scimServiceProviderEndpoint"] = source["scimServiceProviderEndpoint"];
			this["scimSharedSecretExists"] = source["scimSharedSecretExists"];
			this["signSamlRequest"] = source["signSamlRequest"];
			this["ssoType"] = source["ssoType"];
			this["useCustomSPMetadata"] = source["useCustomSPMetadata"];
			this["userSpSigningCertId"] = source["userSpSigningCertId"];
			this["adminMetadata"] = source["adminMetadata"];
			this["userMetadata"] = source["userMetadata"];
		}
	}
	export class UserMetadata {
		certificateUrl?: string;
		spBaseUrl: string;
		spEntityId?: string;
		spMetadataUrl?: string;
		spPostUrl?: string;

		static createFrom(source: any = {}) {
			return new UserMetadata(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["certificateUrl"] = source["certificateUrl"];
			this["spBaseUrl"] = source["spBaseUrl"];
			this["spEntityId"] = source["spEntityId"];
			this["spMetadataUrl"] = source["spMetadataUrl"];
			this["spPostUrl"] = source["spPostUrl"];
		}
	}
}

export namespace index {
	export class Index {
		Segments: Record<string, applicationsegment.ApplicationSegmentResource>;
		SegmentGroups: Record<string, segmentgroup.SegmentGroup>;
		Policies: Record<string, policysetcontrollerv2.PolicyRuleResource>;
		ScimGroups: Record<number, scimgroup.ScimGroup>;
		ServerGroups: Record<string, servergroup.ServerGroup>;
		ScimAttrByID: Record<string, scimattributeheader.ScimAttributeHeader>;
		SegmentToPolicies: Record<string, string[]>;
		GroupToPolicies: Record<string, string[]>;
		DomainToSegments: Record<string, string[]>;
		ScimAttrNameToID: Record<string, string>;
		OrphanSegments: string[];
		DisabledSegments: string[];
		OverlappingDomains: Record<string, string[]>;
		PolicyToScimGroups: Record<string, string[]>;
		ConnectorGroupToPolicies: Record<string, string[]>;
		PolicyToConnectorGroups: Record<string, string[]>;
		ConnectorGroupNames: Record<string, string>;

		static createFrom(source: any = {}) {
			return new Index(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["Segments"] = source["Segments"];
			this["SegmentGroups"] = source["SegmentGroups"];
			this["Policies"] = source["Policies"];
			this["ScimGroups"] = source["ScimGroups"];
			this["ServerGroups"] = source["ServerGroups"];
			this["ScimAttrByID"] = source["ScimAttrByID"];
			this["SegmentToPolicies"] = source["SegmentToPolicies"];
			this["GroupToPolicies"] = source["GroupToPolicies"];
			this["DomainToSegments"] = source["DomainToSegments"];
			this["ScimAttrNameToID"] = source["ScimAttrNameToID"];
			this["OrphanSegments"] = source["OrphanSegments"];
			this["DisabledSegments"] = source["DisabledSegments"];
			this["OverlappingDomains"] = source["OverlappingDomains"];
			this["PolicyToScimGroups"] = source["PolicyToScimGroups"];
			this["ConnectorGroupToPolicies"] = source["ConnectorGroupToPolicies"];
			this["PolicyToConnectorGroups"] = source["PolicyToConnectorGroups"];
			this["ConnectorGroupNames"] = source["ConnectorGroupNames"];
		}
	}
	export class OrphanReport {
		Segment: applicationsegment.ApplicationSegmentResource;
		Groups: string[];

		static createFrom(source: any = {}) {
			return new OrphanReport(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["Segment"] = source["Segment"];
			this["Groups"] = source["Groups"];
		}
	}
	export class OverlapReport {
		Domain: string;
		Segments: applicationsegment.ApplicationSegmentResource[];

		static createFrom(source: any = {}) {
			return new OverlapReport(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["Domain"] = source["Domain"];
			this["Segments"] = source["Segments"];
		}
	}
	export class PolicyCoverage {
		Policy: policysetcontrollerv2.PolicyRuleResource;
		Via: string;

		static createFrom(source: any = {}) {
			return new PolicyCoverage(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["Policy"] = source["Policy"];
			this["Via"] = source["Via"];
		}
	}
	export class ReachabilityResult {
		Domain: string;
		Segments: index.SegmentReachability[];

		static createFrom(source: any = {}) {
			return new ReachabilityResult(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["Domain"] = source["Domain"];
			this["Segments"] = source["Segments"];
		}
	}
	export class SearchResult {
		Type: string;
		ID: string;
		Name: string;
		Matched: string;

		static createFrom(source: any = {}) {
			return new SearchResult(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["Type"] = source["Type"];
			this["ID"] = source["ID"];
			this["Name"] = source["Name"];
			this["Matched"] = source["Matched"];
		}
	}
	export class SegmentReachability {
		Segment: applicationsegment.ApplicationSegmentResource;
		Policies: index.PolicyCoverage[];

		static createFrom(source: any = {}) {
			return new SegmentReachability(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["Segment"] = source["Segment"];
			this["Policies"] = source["Policies"];
		}
	}
}

export namespace logging {
	export class TelemetryBatch {
		events: logging.TelemetryEvent[];

		static createFrom(source: any = {}) {
			return new TelemetryBatch(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["events"] = source["events"];
		}
	}
	export class TelemetryEvent {
		type: string;
		ts: string;
		route?: string;
		error_message?: string;
		error_stack?: string;

		static createFrom(source: any = {}) {
			return new TelemetryEvent(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["type"] = source["type"];
			this["ts"] = source["ts"];
			this["route"] = source["route"];
			this["error_message"] = source["error_message"];
			this["error_stack"] = source["error_stack"];
		}
	}
}

export namespace policysetcontrollerv2 {
	export class Credential {
		id?: string;
		name?: string;

		static createFrom(source: any = {}) {
			return new Credential(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["name"] = source["name"];
		}
	}
	export class DesktopPolicyMappings {
		appSegments?: applicationsegment.ApplicationSegmentResource[];
		id: string;
		creationTime?: string;
		modifiedBy?: string;
		modifiedTime?: string;
		imageId?: string;
		imageName?: string;

		static createFrom(source: any = {}) {
			return new DesktopPolicyMappings(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["appSegments"] = source["appSegments"];
			this["id"] = source["id"];
			this["creationTime"] = source["creationTime"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["imageId"] = source["imageId"];
			this["imageName"] = source["imageName"];
		}
	}
	export class OperandsResourceLHSRHSValue {
		rhs?: string;
		lhs?: string;

		static createFrom(source: any = {}) {
			return new OperandsResourceLHSRHSValue(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["rhs"] = source["rhs"];
			this["lhs"] = source["lhs"];
		}
	}
	export class PolicyRuleResource {
		id?: string;
		name?: string;
		description?: string;
		disabled?: string;
		extranetEnabled?: boolean;
		action?: string;
		actionId?: string;
		postActions?: Record<string, any>;
		creationTime?: string;
		modifiedBy?: string;
		modifiedTime?: string;
		auditMessage?: string;
		customMsg?: string;
		defaultRule?: boolean;
		defaultRuleName?: string;
		operator?: string;
		policySetId?: string;
		policyType?: string;
		priority?: string;
		reauthIdleTimeout?: string;
		reauthTimeout?: string;
		ruleOrder?: string;
		zpnIsolationProfileId?: string;
		zpnInspectionProfileId?: string;
		zpnInspectionProfileName?: string;
		microtenantId: string;
		microtenantName?: string;
		readOnly?: boolean;
		restrictionType?: string;
		zscalerManaged?: boolean;
		devicePostureFailureNotificationEnabled?: boolean;
		conditions: policysetcontrollerv2.PolicyRuleResourceConditions[];
		appServerGroups: servergroup.ServerGroup[];
		appConnectorGroups: appconnectorgroup.AppConnectorGroup[];
		serviceEdgeGroups: serviceedgegroup.ServiceEdgeGroup[];
		desktopPolicyMappings?: policysetcontrollerv2.DesktopPolicyMappings[];
		credential?: policysetcontrollerv2.Credential;
		credentialPool: policysetcontrollerv2.Credential;
		privilegedCapabilities?: policysetcontrollerv2.PrivilegedCapabilities;
		privilegedPortalCapabilities?: policysetcontrollerv2.PrivilegedPortalCapabilities;
		extranetDTO?: common.ExtranetDTO;

		static createFrom(source: any = {}) {
			return new PolicyRuleResource(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["name"] = source["name"];
			this["description"] = source["description"];
			this["disabled"] = source["disabled"];
			this["extranetEnabled"] = source["extranetEnabled"];
			this["action"] = source["action"];
			this["actionId"] = source["actionId"];
			this["postActions"] = source["postActions"];
			this["creationTime"] = source["creationTime"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["auditMessage"] = source["auditMessage"];
			this["customMsg"] = source["customMsg"];
			this["defaultRule"] = source["defaultRule"];
			this["defaultRuleName"] = source["defaultRuleName"];
			this["operator"] = source["operator"];
			this["policySetId"] = source["policySetId"];
			this["policyType"] = source["policyType"];
			this["priority"] = source["priority"];
			this["reauthIdleTimeout"] = source["reauthIdleTimeout"];
			this["reauthTimeout"] = source["reauthTimeout"];
			this["ruleOrder"] = source["ruleOrder"];
			this["zpnIsolationProfileId"] = source["zpnIsolationProfileId"];
			this["zpnInspectionProfileId"] = source["zpnInspectionProfileId"];
			this["zpnInspectionProfileName"] = source["zpnInspectionProfileName"];
			this["microtenantId"] = source["microtenantId"];
			this["microtenantName"] = source["microtenantName"];
			this["readOnly"] = source["readOnly"];
			this["restrictionType"] = source["restrictionType"];
			this["zscalerManaged"] = source["zscalerManaged"];
			this["devicePostureFailureNotificationEnabled"] = source["devicePostureFailureNotificationEnabled"];
			this["conditions"] = source["conditions"];
			this["appServerGroups"] = source["appServerGroups"];
			this["appConnectorGroups"] = source["appConnectorGroups"];
			this["serviceEdgeGroups"] = source["serviceEdgeGroups"];
			this["desktopPolicyMappings"] = source["desktopPolicyMappings"];
			this["credential"] = source["credential"];
			this["credentialPool"] = source["credentialPool"];
			this["privilegedCapabilities"] = source["privilegedCapabilities"];
			this["privilegedPortalCapabilities"] = source["privilegedPortalCapabilities"];
			this["extranetDTO"] = source["extranetDTO"];
		}
	}
	export class PolicyRuleResourceConditions {
		id?: string;
		creationTime?: string;
		modifiedBy?: string;
		modifiedTime?: string;
		negated: boolean;
		operator?: string;
		operands?: policysetcontrollerv2.PolicyRuleResourceOperands[];

		static createFrom(source: any = {}) {
			return new PolicyRuleResourceConditions(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["creationTime"] = source["creationTime"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["negated"] = source["negated"];
			this["operator"] = source["operator"];
			this["operands"] = source["operands"];
		}
	}
	export class PolicyRuleResourceOperands {
		id?: string;
		creationTime?: string;
		modifiedBy?: string;
		modifiedTime?: string;
		objectType?: string;
		values?: string[];
		idpId?: string;
		lhs?: string;
		rhs?: string;
		entryValues?: policysetcontrollerv2.OperandsResourceLHSRHSValue[];

		static createFrom(source: any = {}) {
			return new PolicyRuleResourceOperands(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["creationTime"] = source["creationTime"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["objectType"] = source["objectType"];
			this["values"] = source["values"];
			this["idpId"] = source["idpId"];
			this["lhs"] = source["lhs"];
			this["rhs"] = source["rhs"];
			this["entryValues"] = source["entryValues"];
		}
	}
	export class PrivilegedCapabilities {
		id: string;
		creationTime?: string;
		modifiedBy?: string;
		modifiedTime?: string;
		microtenantId: string;
		capabilities?: string[];

		static createFrom(source: any = {}) {
			return new PrivilegedCapabilities(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["creationTime"] = source["creationTime"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["microtenantId"] = source["microtenantId"];
			this["capabilities"] = source["capabilities"];
		}
	}
	export class PrivilegedPortalCapabilities {
		capabilities?: string[];
		microtenantId?: string;

		static createFrom(source: any = {}) {
			return new PrivilegedPortalCapabilities(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["capabilities"] = source["capabilities"];
			this["microtenantId"] = source["microtenantId"];
		}
	}
}

export namespace postureprofile {
	export class PostureProfile {
		id?: string;
		name?: string;
		applyToMachineTunnelEnabled: boolean;
		crlCheckEnabled: boolean;
		nonExportablePrivateKeyEnabled: boolean;
		platform?: string;
		creationTime?: string;
		domain?: string;
		masterCustomerId?: string;
		modifiedBy?: string;
		modifiedTime?: string;
		postureType?: string;
		postureUdid?: string;
		rootCert?: string;
		zscalerCloud?: string;
		zscalerCustomerId?: string;

		static createFrom(source: any = {}) {
			return new PostureProfile(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["name"] = source["name"];
			this["applyToMachineTunnelEnabled"] = source["applyToMachineTunnelEnabled"];
			this["crlCheckEnabled"] = source["crlCheckEnabled"];
			this["nonExportablePrivateKeyEnabled"] = source["nonExportablePrivateKeyEnabled"];
			this["platform"] = source["platform"];
			this["creationTime"] = source["creationTime"];
			this["domain"] = source["domain"];
			this["masterCustomerId"] = source["masterCustomerId"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["postureType"] = source["postureType"];
			this["postureUdid"] = source["postureUdid"];
			this["rootCert"] = source["rootCert"];
			this["zscalerCloud"] = source["zscalerCloud"];
			this["zscalerCustomerId"] = source["zscalerCustomerId"];
		}
	}
}

export namespace scimattributeheader {
	export class ScimAttributeHeader {
		canonicalValues?: string[];
		caseSensitive?: boolean;
		creationTime?: string;
		dataType?: string;
		description?: string;
		id?: string;
		idpId?: string;
		modifiedBy?: string;
		modifiedTime?: string;
		multivalued?: boolean;
		mutability?: string;
		name?: string;
		required?: boolean;
		returned?: string;
		schemaURI?: string;
		uniqueness?: boolean;

		static createFrom(source: any = {}) {
			return new ScimAttributeHeader(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["canonicalValues"] = source["canonicalValues"];
			this["caseSensitive"] = source["caseSensitive"];
			this["creationTime"] = source["creationTime"];
			this["dataType"] = source["dataType"];
			this["description"] = source["description"];
			this["id"] = source["id"];
			this["idpId"] = source["idpId"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["multivalued"] = source["multivalued"];
			this["mutability"] = source["mutability"];
			this["name"] = source["name"];
			this["required"] = source["required"];
			this["returned"] = source["returned"];
			this["schemaURI"] = source["schemaURI"];
			this["uniqueness"] = source["uniqueness"];
		}
	}
}

export namespace scimgroup {
	export class ScimGroup {
		creationTime?: number;
		id?: number;
		idpGroupId?: string;
		idpId?: number;
		idpName?: string;
		modifiedTime?: number;
		name?: string;
		internalId?: string;

		static createFrom(source: any = {}) {
			return new ScimGroup(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["creationTime"] = source["creationTime"];
			this["id"] = source["id"];
			this["idpGroupId"] = source["idpGroupId"];
			this["idpId"] = source["idpId"];
			this["idpName"] = source["idpName"];
			this["modifiedTime"] = source["modifiedTime"];
			this["name"] = source["name"];
			this["internalId"] = source["internalId"];
		}
	}
}

export namespace segmentgroup {
	export class AppServerGroup {
		configSpace?: string;
		creationTime?: string;
		description?: string;
		enabled: boolean;
		id?: string;
		dynamicDiscovery: boolean;
		modifiedBy?: string;
		modifiedTime?: string;
		name: string;

		static createFrom(source: any = {}) {
			return new AppServerGroup(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["configSpace"] = source["configSpace"];
			this["creationTime"] = source["creationTime"];
			this["description"] = source["description"];
			this["enabled"] = source["enabled"];
			this["id"] = source["id"];
			this["dynamicDiscovery"] = source["dynamicDiscovery"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["name"] = source["name"];
		}
	}
	export class Application {
		bypassType?: string;
		configSpace?: string;
		creationTime?: string;
		defaultIdleTimeout?: string;
		defaultMaxAge?: string;
		description?: string;
		domainName?: string;
		domainNames?: string[];
		doubleEncrypt: boolean;
		enabled: boolean;
		healthCheckType?: string;
		id?: string;
		ipAnchored: boolean;
		logFeatures?: string[];
		modifiedBy?: string;
		modifiedTime?: string;
		name: string;
		passiveHealthEnabled: boolean;
		serverGroups?: segmentgroup.AppServerGroup[];
		tcpPortRanges?: any;
		tcpPortsIn?: any;
		tcpPortsOut?: any;
		udpPortRangesg?: any;

		static createFrom(source: any = {}) {
			return new Application(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["bypassType"] = source["bypassType"];
			this["configSpace"] = source["configSpace"];
			this["creationTime"] = source["creationTime"];
			this["defaultIdleTimeout"] = source["defaultIdleTimeout"];
			this["defaultMaxAge"] = source["defaultMaxAge"];
			this["description"] = source["description"];
			this["domainName"] = source["domainName"];
			this["domainNames"] = source["domainNames"];
			this["doubleEncrypt"] = source["doubleEncrypt"];
			this["enabled"] = source["enabled"];
			this["healthCheckType"] = source["healthCheckType"];
			this["id"] = source["id"];
			this["ipAnchored"] = source["ipAnchored"];
			this["logFeatures"] = source["logFeatures"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["name"] = source["name"];
			this["passiveHealthEnabled"] = source["passiveHealthEnabled"];
			this["serverGroups"] = source["serverGroups"];
			this["tcpPortRanges"] = source["tcpPortRanges"];
			this["tcpPortsIn"] = source["tcpPortsIn"];
			this["tcpPortsOut"] = source["tcpPortsOut"];
			this["udpPortRangesg"] = source["udpPortRangesg"];
		}
	}
	export class ApplicationNames {
		id?: string;
		name: string;

		static createFrom(source: any = {}) {
			return new ApplicationNames(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["name"] = source["name"];
		}
	}
	export class SegmentGroup {
		id?: string;
		name: string;
		description?: string;
		enabled: boolean;
		configSpace?: string;
		creationTime?: string;
		modifiedBy?: string;
		modifiedTime?: string;
		policyMigrated: boolean;
		tcpKeepAliveEnabled?: string;
		microtenantId?: string;
		microtenantName?: string;
		addedApps?: string;
		deletedApps?: string;
		applications: segmentgroup.Application[];
		applicationNames?: segmentgroup.ApplicationNames[];

		static createFrom(source: any = {}) {
			return new SegmentGroup(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["name"] = source["name"];
			this["description"] = source["description"];
			this["enabled"] = source["enabled"];
			this["configSpace"] = source["configSpace"];
			this["creationTime"] = source["creationTime"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["policyMigrated"] = source["policyMigrated"];
			this["tcpKeepAliveEnabled"] = source["tcpKeepAliveEnabled"];
			this["microtenantId"] = source["microtenantId"];
			this["microtenantName"] = source["microtenantName"];
			this["addedApps"] = source["addedApps"];
			this["deletedApps"] = source["deletedApps"];
			this["applications"] = source["applications"];
			this["applicationNames"] = source["applicationNames"];
		}
	}
}

export namespace server {
	export class About {
		version: string;
		commit: string;
		date: string;
		demo: boolean;

		static createFrom(source: any = {}) {
			return new About(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["version"] = source["version"];
			this["commit"] = source["commit"];
			this["date"] = source["date"];
			this["demo"] = source["demo"];
		}
	}
	export class CompareRequest {
		context: simulator.SimContext;
		virtualPolicy: server.VirtualPolicyInput;

		static createFrom(source: any = {}) {
			return new CompareRequest(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["context"] = source["context"];
			this["virtualPolicy"] = source["virtualPolicy"];
		}
	}
	export class CompareResult {
		baseline: simulator.DecisionResult;
		withVirtual: simulator.DecisionResult;
		virtualRule: policysetcontrollerv2.PolicyRuleResource;

		static createFrom(source: any = {}) {
			return new CompareResult(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["baseline"] = source["baseline"];
			this["withVirtual"] = source["withVirtual"];
			this["virtualRule"] = source["virtualRule"];
		}
	}
	export class Identity {
		user: string;
		email: string;
		groups: string;
		name: string;

		static createFrom(source: any = {}) {
			return new Identity(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["user"] = source["user"];
			this["email"] = source["email"];
			this["groups"] = source["groups"];
			this["name"] = source["name"];
		}
	}
	export class Libraries {
		go: string;
		backend: server.Library[];

		static createFrom(source: any = {}) {
			return new Libraries(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["go"] = source["go"];
			this["backend"] = source["backend"];
		}
	}
	export class Library {
		name: string;
		version: string;

		static createFrom(source: any = {}) {
			return new Library(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["name"] = source["name"];
			this["version"] = source["version"];
		}
	}
	export class VirtualPolicyInput {
		name: string;
		action: string;
		priority: string;
		scimGroupIds?: string[];
		segmentIds?: string[];
		segmentGroupIds?: string[];

		static createFrom(source: any = {}) {
			return new VirtualPolicyInput(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["name"] = source["name"];
			this["action"] = source["action"];
			this["priority"] = source["priority"];
			this["scimGroupIds"] = source["scimGroupIds"];
			this["segmentIds"] = source["segmentIds"];
			this["segmentGroupIds"] = source["segmentGroupIds"];
		}
	}
}

export namespace servergroup {
	export class Applications {
		id?: string;
		name?: string;

		static createFrom(source: any = {}) {
			return new Applications(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["name"] = source["name"];
		}
	}
	export class ServerGroup {
		id?: string;
		enabled: boolean;
		name?: string;
		description?: string;
		ipAnchored: boolean;
		configSpace?: string;
		dynamicDiscovery: boolean;
		extranetEnabled: boolean;
		creationTime?: string;
		modifiedBy?: string;
		modifiedTime?: string;
		microtenantId?: string;
		microtenantName?: string;
		readOnly?: boolean;
		restrictionType?: string;
		zscalerManaged?: boolean;
		appConnectorGroups: appconnectorgroup.AppConnectorGroup[];
		servers: appservercontroller.ApplicationServer[];
		applications: servergroup.Applications[];
		extranetDTO?: common.ExtranetDTO;

		static createFrom(source: any = {}) {
			return new ServerGroup(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["enabled"] = source["enabled"];
			this["name"] = source["name"];
			this["description"] = source["description"];
			this["ipAnchored"] = source["ipAnchored"];
			this["configSpace"] = source["configSpace"];
			this["dynamicDiscovery"] = source["dynamicDiscovery"];
			this["extranetEnabled"] = source["extranetEnabled"];
			this["creationTime"] = source["creationTime"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["microtenantId"] = source["microtenantId"];
			this["microtenantName"] = source["microtenantName"];
			this["readOnly"] = source["readOnly"];
			this["restrictionType"] = source["restrictionType"];
			this["zscalerManaged"] = source["zscalerManaged"];
			this["appConnectorGroups"] = source["appConnectorGroups"];
			this["servers"] = source["servers"];
			this["applications"] = source["applications"];
			this["extranetDTO"] = source["extranetDTO"];
		}
	}
}

export namespace serviceedgecontroller {
	export class PrivateBrokerVersion {
		id?: string;
		applicationStartTime?: string;
		brokerId?: string;
		creationTime?: string;
		ctrlChannelStatus?: string;
		currentVersion?: string;
		disableAutoUpdate?: boolean;
		lastConnectTime?: string;
		lastDisconnectTime?: string;
		lastUpgradedTime?: string;
		loneWarrior?: boolean;
		modifiedBy?: string;
		modifiedTime?: string;
		platform?: string;
		platformDetail?: string;
		previousVersion?: string;
		serviceEdgeGroupId?: string;
		privateIp?: string;
		publicIp?: string;
		restartInstructions?: string;
		restartTimeInSec?: string;
		runtimeOS?: string;
		sargeVersion?: string;
		systemStartTime?: string;
		tunnelId?: string;
		upgradeAttempt?: string;
		upgradeStatus?: string;
		upgradeNowOnce?: boolean;
		zpnSubModuleUpgradeList?: common.ZPNSubModuleUpgrade[];

		static createFrom(source: any = {}) {
			return new PrivateBrokerVersion(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["applicationStartTime"] = source["applicationStartTime"];
			this["brokerId"] = source["brokerId"];
			this["creationTime"] = source["creationTime"];
			this["ctrlChannelStatus"] = source["ctrlChannelStatus"];
			this["currentVersion"] = source["currentVersion"];
			this["disableAutoUpdate"] = source["disableAutoUpdate"];
			this["lastConnectTime"] = source["lastConnectTime"];
			this["lastDisconnectTime"] = source["lastDisconnectTime"];
			this["lastUpgradedTime"] = source["lastUpgradedTime"];
			this["loneWarrior"] = source["loneWarrior"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["platform"] = source["platform"];
			this["platformDetail"] = source["platformDetail"];
			this["previousVersion"] = source["previousVersion"];
			this["serviceEdgeGroupId"] = source["serviceEdgeGroupId"];
			this["privateIp"] = source["privateIp"];
			this["publicIp"] = source["publicIp"];
			this["restartInstructions"] = source["restartInstructions"];
			this["restartTimeInSec"] = source["restartTimeInSec"];
			this["runtimeOS"] = source["runtimeOS"];
			this["sargeVersion"] = source["sargeVersion"];
			this["systemStartTime"] = source["systemStartTime"];
			this["tunnelId"] = source["tunnelId"];
			this["upgradeAttempt"] = source["upgradeAttempt"];
			this["upgradeStatus"] = source["upgradeStatus"];
			this["upgradeNowOnce"] = source["upgradeNowOnce"];
			this["zpnSubModuleUpgradeList"] = source["zpnSubModuleUpgradeList"];
		}
	}
	export class ServiceEdgeController {
		applicationStartTime?: string;
		serviceEdgeGroupId?: string;
		serviceEdgeGroupName?: string;
		controlChannelStatus?: string;
		creationTime?: string;
		ctrlBrokerName?: string;
		currentVersion?: string;
		description?: string;
		enabled?: boolean;
		expectedUpgradeTime?: string;
		expectedVersion?: string;
		fingerprint?: string;
		id?: string;
		ipAcl?: string;
		issuedCertId?: string;
		lastBrokerConnectTime?: string;
		lastBrokerConnectTimeDuration?: string;
		lastBrokerDisconnectTime?: string;
		lastBrokerDisconnectTimeDuration?: string;
		lastUpgradeTime?: string;
		latitude?: string;
		location?: string;
		longitude?: string;
		listenIps?: string[];
		modifiedBy?: string;
		modifiedTime?: string;
		name?: string;
		provisioningKeyId: string;
		provisioningKeyName: string;
		platform?: string;
		platformDetail?: string;
		previousVersion?: string;
		privateIp?: string;
		publicIp?: string;
		publishIps?: string[];
		publishIpv6?: boolean;
		runtimeOS?: string;
		sargeVersion?: string;
		enrollmentCert?: Record<string, any>;
		upgradeAttempt?: string;
		upgradeStatus?: string;
		microtenantId?: string;
		microtenantName?: string;
		privateBrokerVersion?: serviceedgecontroller.PrivateBrokerVersion;

		static createFrom(source: any = {}) {
			return new ServiceEdgeController(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["applicationStartTime"] = source["applicationStartTime"];
			this["serviceEdgeGroupId"] = source["serviceEdgeGroupId"];
			this["serviceEdgeGroupName"] = source["serviceEdgeGroupName"];
			this["controlChannelStatus"] = source["controlChannelStatus"];
			this["creationTime"] = source["creationTime"];
			this["ctrlBrokerName"] = source["ctrlBrokerName"];
			this["currentVersion"] = source["currentVersion"];
			this["description"] = source["description"];
			this["enabled"] = source["enabled"];
			this["expectedUpgradeTime"] = source["expectedUpgradeTime"];
			this["expectedVersion"] = source["expectedVersion"];
			this["fingerprint"] = source["fingerprint"];
			this["id"] = source["id"];
			this["ipAcl"] = source["ipAcl"];
			this["issuedCertId"] = source["issuedCertId"];
			this["lastBrokerConnectTime"] = source["lastBrokerConnectTime"];
			this["lastBrokerConnectTimeDuration"] = source["lastBrokerConnectTimeDuration"];
			this["lastBrokerDisconnectTime"] = source["lastBrokerDisconnectTime"];
			this["lastBrokerDisconnectTimeDuration"] = source["lastBrokerDisconnectTimeDuration"];
			this["lastUpgradeTime"] = source["lastUpgradeTime"];
			this["latitude"] = source["latitude"];
			this["location"] = source["location"];
			this["longitude"] = source["longitude"];
			this["listenIps"] = source["listenIps"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["name"] = source["name"];
			this["provisioningKeyId"] = source["provisioningKeyId"];
			this["provisioningKeyName"] = source["provisioningKeyName"];
			this["platform"] = source["platform"];
			this["platformDetail"] = source["platformDetail"];
			this["previousVersion"] = source["previousVersion"];
			this["privateIp"] = source["privateIp"];
			this["publicIp"] = source["publicIp"];
			this["publishIps"] = source["publishIps"];
			this["publishIpv6"] = source["publishIpv6"];
			this["runtimeOS"] = source["runtimeOS"];
			this["sargeVersion"] = source["sargeVersion"];
			this["enrollmentCert"] = source["enrollmentCert"];
			this["upgradeAttempt"] = source["upgradeAttempt"];
			this["upgradeStatus"] = source["upgradeStatus"];
			this["microtenantId"] = source["microtenantId"];
			this["microtenantName"] = source["microtenantName"];
			this["privateBrokerVersion"] = source["privateBrokerVersion"];
		}
	}
}

export namespace serviceedgegroup {
	export class ServiceEdgeGroup {
		id?: string;
		name?: string;
		description?: string;
		enabled: boolean;
		cityCountry?: string;
		city?: string;
		countryCode?: string;
		creationTime?: string;
		geoLocationId?: string;
		graceDistanceEnabled: boolean;
		graceDistanceValue?: string;
		graceDistanceValueUnit?: string;
		isPublic?: string;
		latitude?: string;
		location?: string;
		longitude?: string;
		modifiedBy?: string;
		modifiedTime?: string;
		useInDrMode: boolean;
		overrideVersionProfile: boolean;
		upgradeDay?: string;
		upgradeTimeInSecs?: string;
		versionProfileId?: string;
		versionProfileName?: string;
		versionProfileVisibilityScope?: string;
		objectType?: string;
		scopeName?: string;
		restrictedEntity?: boolean;
		altCloud?: string;
		microtenantId?: string;
		microtenantName?: string;
		siteId?: string;
		siteName?: string;
		readOnly?: boolean;
		restrictionType?: string;
		zscalerManaged?: boolean;
		exclusiveForBusinessContinuity?: boolean;
		nameWithoutTrim?: string;
		serviceEdges?: serviceedgecontroller.ServiceEdgeController[];
		trustedNetworks?: trustednetwork.TrustedNetwork[];
		enrollmentCertId?: string;

		static createFrom(source: any = {}) {
			return new ServiceEdgeGroup(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["name"] = source["name"];
			this["description"] = source["description"];
			this["enabled"] = source["enabled"];
			this["cityCountry"] = source["cityCountry"];
			this["city"] = source["city"];
			this["countryCode"] = source["countryCode"];
			this["creationTime"] = source["creationTime"];
			this["geoLocationId"] = source["geoLocationId"];
			this["graceDistanceEnabled"] = source["graceDistanceEnabled"];
			this["graceDistanceValue"] = source["graceDistanceValue"];
			this["graceDistanceValueUnit"] = source["graceDistanceValueUnit"];
			this["isPublic"] = source["isPublic"];
			this["latitude"] = source["latitude"];
			this["location"] = source["location"];
			this["longitude"] = source["longitude"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["useInDrMode"] = source["useInDrMode"];
			this["overrideVersionProfile"] = source["overrideVersionProfile"];
			this["upgradeDay"] = source["upgradeDay"];
			this["upgradeTimeInSecs"] = source["upgradeTimeInSecs"];
			this["versionProfileId"] = source["versionProfileId"];
			this["versionProfileName"] = source["versionProfileName"];
			this["versionProfileVisibilityScope"] = source["versionProfileVisibilityScope"];
			this["objectType"] = source["objectType"];
			this["scopeName"] = source["scopeName"];
			this["restrictedEntity"] = source["restrictedEntity"];
			this["altCloud"] = source["altCloud"];
			this["microtenantId"] = source["microtenantId"];
			this["microtenantName"] = source["microtenantName"];
			this["siteId"] = source["siteId"];
			this["siteName"] = source["siteName"];
			this["readOnly"] = source["readOnly"];
			this["restrictionType"] = source["restrictionType"];
			this["zscalerManaged"] = source["zscalerManaged"];
			this["exclusiveForBusinessContinuity"] = source["exclusiveForBusinessContinuity"];
			this["nameWithoutTrim"] = source["nameWithoutTrim"];
			this["serviceEdges"] = source["serviceEdges"];
			this["trustedNetworks"] = source["trustedNetworks"];
			this["enrollmentCertId"] = source["enrollmentCertId"];
		}
	}
}

export namespace simulator {
	export class ConditionResult {
		condition_id?: string;
		operator?: string;
		negated?: boolean;
		operands?: simulator.OperandResult[];
		result?: boolean;

		static createFrom(source: any = {}) {
			return new ConditionResult(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["condition_id"] = source["condition_id"];
			this["operator"] = source["operator"];
			this["negated"] = source["negated"];
			this["operands"] = source["operands"];
			this["result"] = source["result"];
		}
	}
	export class DecisionResult {
		action?: string;
		matched_rule?: policysetcontrollerv2.PolicyRuleResource;
		trace?: simulator.RuleTrace[];
		warnings?: string[];

		static createFrom(source: any = {}) {
			return new DecisionResult(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["action"] = source["action"];
			this["matched_rule"] = source["matched_rule"];
			this["trace"] = source["trace"];
			this["warnings"] = source["warnings"];
		}
	}
	export class OperandResult {
		object_type?: string;
		matched?: boolean;
		skipped?: boolean;
		match_reason?: string;

		static createFrom(source: any = {}) {
			return new OperandResult(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["object_type"] = source["object_type"];
			this["matched"] = source["matched"];
			this["skipped"] = source["skipped"];
			this["match_reason"] = source["match_reason"];
		}
	}
	export class RuleTrace {
		rule_id?: string;
		rule_name?: string;
		priority?: number;
		action?: string;
		matched?: boolean;
		skip_reason?: string;
		conditions?: simulator.ConditionResult[];

		static createFrom(source: any = {}) {
			return new RuleTrace(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["rule_id"] = source["rule_id"];
			this["rule_name"] = source["rule_name"];
			this["priority"] = source["priority"];
			this["action"] = source["action"];
			this["matched"] = source["matched"];
			this["skip_reason"] = source["skip_reason"];
			this["conditions"] = source["conditions"];
		}
	}
	export class SimContext {
		scim_group_ids?: string[];
		scim_attrs?: Record<string, string>;
		segment_id?: string;
		segment_group_id?: string;
		client_type?: string;
		trusted_network?: string;
		platform?: string;
		fqdn?: string;

		static createFrom(source: any = {}) {
			return new SimContext(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["scim_group_ids"] = source["scim_group_ids"];
			this["scim_attrs"] = source["scim_attrs"];
			this["segment_id"] = source["segment_id"];
			this["segment_group_id"] = source["segment_group_id"];
			this["client_type"] = source["client_type"];
			this["trusted_network"] = source["trusted_network"];
			this["platform"] = source["platform"];
			this["fqdn"] = source["fqdn"];
		}
	}
}

export namespace storage {
	export class SimulationRun {
		id: number;
		created_at: string;
		context_json: string;
		action: string;
		matched_rule_id: string;
		matched_rule_name: string;
		result_json: string;
		created_by: string;

		static createFrom(source: any = {}) {
			return new SimulationRun(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["id"] = source["id"];
			this["created_at"] = source["created_at"];
			this["context_json"] = source["context_json"];
			this["action"] = source["action"];
			this["matched_rule_id"] = source["matched_rule_id"];
			this["matched_rule_name"] = source["matched_rule_name"];
			this["result_json"] = source["result_json"];
			this["created_by"] = source["created_by"];
		}
	}
}

export namespace trustednetwork {
	export class TrustedNetwork {
		creationTime?: string;
		domain?: string;
		id?: string;
		masterCustomerId?: string;
		modifiedBy?: string;
		modifiedTime?: string;
		name?: string;
		networkId?: string;
		zscalerCloud?: string;

		static createFrom(source: any = {}) {
			return new TrustedNetwork(source);
		}

		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this["creationTime"] = source["creationTime"];
			this["domain"] = source["domain"];
			this["id"] = source["id"];
			this["masterCustomerId"] = source["masterCustomerId"];
			this["modifiedBy"] = source["modifiedBy"];
			this["modifiedTime"] = source["modifiedTime"];
			this["name"] = source["name"];
			this["networkId"] = source["networkId"];
			this["zscalerCloud"] = source["zscalerCloud"];
		}
	}
}

