import {
  type Renderer,
  boolRenderer,
  labelArrayRenderer,
  timestampRenderer,
} from "./renderers";

type Entry =
  | string
  | {
      key: string;
      label?: string;
      visible?: boolean;
      render?: Renderer;
    };

export type TableKey =
  | "appconnectors"
  | "appconnectorgroups"
  | "appgroups"
  | "applications"
  | "policies"
  | "postureprofiles"
  | "scimgroups"
  | "servergroups"
  | "trustednetworks"
  | "scimattributes"
  | "simulationruns"
  | "certificates";

export const columnDefs: Record<TableKey, Entry[]> = {
  appconnectors: [
    { key: "id", visible: false },
    "name",
    { key: "description", visible: false },
    { key: "enabled", render: boolRenderer },
    { key: "appConnectorGroupName", label: "Group" },
    { key: "controlChannelStatus", label: "Status" },
    "privateIp",
    "publicIp",
    { key: "platform", visible: false },
    { key: "currentVersion", label: "Version" },
    { key: "upgradeStatus", visible: false },
    { key: "location", visible: false },
    { key: "lastBrokerConnectTime", label: "Last Connected", visible: false, render: timestampRenderer },
    { key: "creationTime", label: "Created", visible: false, render: timestampRenderer },
    { key: "modifiedTime", label: "Modified", visible: false, render: timestampRenderer },
    { key: "microtenantName", label: "Microtenant", visible: false },
  ],
  appconnectorgroups: [
    { key: "id", visible: false },
    "name",
    { key: "description", visible: false },
    { key: "enabled", render: boolRenderer },
    { key: "cityCountry", label: "Location" },
    { key: "countryCode", label: "Country", visible: false },
    { key: "versionProfileName", label: "Version Profile" },
    { key: "upgradeDay", visible: false },
    { key: "praEnabled", visible: false, render: boolRenderer },
    { key: "lssAppConnectorGroup", label: "LSS Group", visible: false, render: boolRenderer },
    { key: "useInDrMode", label: "DR Mode", visible: false, render: boolRenderer },
    { key: "creationTime", label: "Created", visible: false, render: timestampRenderer },
    { key: "modifiedTime", label: "Modified", visible: false, render: timestampRenderer },
    { key: "microtenantName", label: "Microtenant", visible: false },
  ],
  appgroups: [
    { key: "id", visible: false },
    "name",
    { key: "description", visible: false },
    { key: "enabled", render: boolRenderer },
    { key: "configSpace", visible: false },
    { key: "creationTime", visible: false, render: timestampRenderer },
    { key: "modifiedBy", visible: false },
    { key: "modifiedTime", render: timestampRenderer },
    { key: "policyMigrated", visible: false },
    { key: "tcpKeepAliveEnabled", visible: false },
    { key: "microtenantId", visible: false },
    { key: "microtenantName", visible: false },
    { key: "addedApps", visible: false },
    { key: "deletedApps", visible: false },
    { key: "applications", visible: false },
    { key: "applicationNames", visible: false },
  ],
  applications: [
    { key: "id", visible: false },
    { key: "domainNames", label: "Domains", render: labelArrayRenderer },
    "name",
    { key: "description", visible: false },
    { key: "enabled", render: boolRenderer },
    { key: "extranetEnabled", label: "Extranet", visible: false, render: boolRenderer },
    { key: "apiProtectionEnabled", visible: false },
    { key: "autoAppProtectEnabled", visible: false },
    { key: "adpEnabled", visible: false },
    { key: "passiveHealthEnabled", visible: false },
    { key: "doubleEncrypt", visible: false, render: boolRenderer },
    { key: "configSpace", visible: false },
    { key: "applications", visible: false },
    "bypassType",
    { key: "bypassOnReauth", visible: false },
    { key: "healthCheckType", label: "Health Check", visible: false },
    { key: "isCnameEnabled", visible: false },
    { key: "ipAnchored", visible: false, render: boolRenderer },
    { key: "fqdnDnsCheck", visible: false },
    { key: "healthReporting", visible: false },
    { key: "selectConnectorCloseToApp", visible: false },
    { key: "icmpAccessType", visible: false },
    { key: "appRecommendationId", visible: false },
    { key: "segmentGroupId", visible: false },
    { key: "segmentGroupName", label: "Segment Group" },
    { key: "creationTime", label: "Created", visible: false, render: timestampRenderer },
    { key: "modifiedBy", visible: false },
    { key: "modifiedTime", label: "Modified", render: timestampRenderer },
    { key: "tcpKeepAlive", visible: false },
    { key: "isIncompleteDRConfig", visible: false },
    { key: "useInDrMode", visible: false },
    { key: "inspectTrafficWithZia", visible: false },
    { key: "weightedLoadBalancing", visible: false },
    { key: "microtenantId", visible: false },
    { key: "microtenantName", label: "Microtenant", visible: false },
    { key: "matchStyle", visible: false },
    { key: "readOnly", visible: false },
    { key: "restrictionType", visible: false },
    { key: "zscalerManaged", visible: false },
    { key: "tcpPortRanges", label: "TCP Ports", visible: false, render: labelArrayRenderer },
    { key: "udpPortRanges", label: "UDP Ports", visible: false, render: labelArrayRenderer },
    { key: "tcpPortRange", visible: false },
    { key: "udpPortRange", visible: false },
    { key: "serverGroups", visible: false },
    { key: "defaultIdleTimeout", visible: false },
    { key: "defaultMaxAge", visible: false },
    { key: "clientlessApps", visible: false },
    { key: "shareToMicrotenants", visible: false },
    { key: "sharedMicrotenantDetails", visible: false },
    { key: "zpnErId", visible: false },
    { key: "tags", visible: false },
    { key: "policyStyle", visible: false },
  ],
  policies: [
    { key: "id", visible: false },
    "name",
    { key: "description", visible: false },
    { key: "disabled", visible: false },
    { key: "extranetEnabled", visible: false },
    "action",
    { key: "actionId", visible: false },
    "postActions",
    { key: "creationTime", visible: false },
    { key: "modifiedBy", visible: false },
    { key: "modifiedTime", label: "Modified", render: timestampRenderer },
    { key: "auditMessage", visible: false },
    { key: "customMsg", visible: false },
    { key: "defaultRule", visible: false },
    { key: "defaultRuleName", visible: false },
    { key: "operator", visible: false },
    { key: "policySetId", visible: false },
    { key: "policyType", label: "Type" },
    "priority",
    { key: "reauthIdleTimeout", visible: false },
    { key: "reauthTimeout", visible: false },
    { key: "zpnIsolationProfileId", visible: false },
    { key: "zpnInspectionProfileId", visible: false },
    { key: "zpnInspectionProfileName", visible: false },
    { key: "microtenantId", visible: false },
    { key: "microtenantName", visible: false },
    { key: "readOnly", visible: false },
    { key: "restrictionType", visible: false },
    { key: "zscalerManaged", visible: false },
    { key: "devicePostureFailureNotificationEnabled", visible: false },
    "conditions",
    { key: "appServerGroups", visible: false },
    { key: "appConnectorGroups", visible: false },
    { key: "serviceEdgeGroups", visible: false },
    { key: "desktopPolicyMappings", visible: false },
    { key: "credential", visible: false },
    { key: "credentialPool", visible: false },
    { key: "privilegedCapabilities", visible: false },
    { key: "privilegedPortalCapabilities", visible: false },
    { key: "extranetDTO", visible: false },
  ],
  postureprofiles: [
    { key: "id", visible: false },
    "name",
    { key: "applyToMachineTunnelEnabled", visible: false },
    { key: "crlCheckEnabled", visible: false },
    { key: "nonExportablePrivateKeyEnabled", visible: false },
    "platform",
    { key: "creationTime", visible: false },
    "domain",
    { key: "masterCustomerId", visible: false },
    { key: "modifiedBy", visible: false },
    { key: "modifiedTime", label: "Modified", render: timestampRenderer },
    { key: "postureType", label: "Type" },
    { key: "postureUdid", visible: false },
    { key: "rootCert", visible: false },
    { key: "zscalerCloud", visible: false },
    { key: "zscalerCustomerId", visible: false },
  ],
  scimgroups: [
    { key: "creationTime", visible: false },
    "id",
    { key: "idpGroupId", visible: false },
    { key: "idpId", visible: false },
    { key: "idpName", visible: false },
    { key: "modifiedTime", label: "Modified", render: timestampRenderer },
    "name",
    { key: "internalId", visible: false },
  ],
  servergroups: [
    { key: "id", visible: false },
    { key: "enabled", render: boolRenderer },
    "name",
    { key: "description", visible: false },
    { key: "ipAnchored", visible: false, render: boolRenderer },
    { key: "configSpace", visible: false },
    { key: "dynamicDiscovery", render: boolRenderer },
    { key: "extranetEnabled", visible: false },
    { key: "creationTime", visible: false },
    { key: "modifiedBy", visible: false },
    { key: "modifiedTime", label: "Modified", render: timestampRenderer },
    { key: "microtenantId", visible: false },
    { key: "microtenantName", visible: false },
    { key: "readOnly", visible: false },
    { key: "restrictionType", visible: false },
    { key: "zscalerManaged", visible: false },
    { key: "appConnectorGroups", visible: false },
    { key: "servers", visible: false },
    { key: "applications", visible: false },
    { key: "extranetDTO", visible: false },
  ],
  trustednetworks: [
    { key: "creationTime", visible: false },
    { key: "domain", visible: false },
    { key: "id", visible: false },
    { key: "masterCustomerId", visible: false },
    { key: "modifiedBy", visible: false },
    { key: "modifiedTime", label: "Modified", render: timestampRenderer },
    "name",
    { key: "networkId", visible: false },
    { key: "zscalerCloud", label: "Cloud", visible: false },
  ],
  scimattributes: [
    { key: "id", visible: false },
    "name",
    "dataType",
    { key: "description", visible: false },
    { key: "idpId", label: "IDP" },
    { key: "caseSensitive", visible: false, render: boolRenderer },
    { key: "multivalued", label: "Multi-valued", visible: false, render: boolRenderer },
    { key: "mutability", visible: false },
    { key: "returned", visible: false },
    { key: "schemaURI", visible: false },
    { key: "creationTime", label: "Created", visible: false, render: timestampRenderer },
    { key: "modifiedTime", label: "Modified", render: timestampRenderer },
  ],
  simulationruns: [
    "id",
    { key: "created_at", render: timestampRenderer },
    { key: "context_json", visible: false },
    "action",
    { key: "matched_rule_id", visible: false },
    "matched_rule_name",
    { key: "result_json", visible: false },
  ],
  certificates: [
    { key: "id", visible: false },
    "name",
    "description",
    { key: "cName", label: "Common Name" },
    { key: "certChain", visible: false },
    { key: "certBlob", visible: false },
    { key: "certificate", visible: false },
    { key: "publicKey", visible: false },
    "creationTime",
    "issuedBy",
    "issuedTo",
    { key: "modifiedBy", visible: false },
    { key: "modifiedTime", visible: false },
    "san",
    { key: "serialNo", visible: false },
    "status",
    { key: "validFromInEpochSec", label: "Valid From" },
    { key: "validToInEpochSec", label: "Valid To" },
    { key: "microtenantId", visible: false },
    { key: "microtenantName", visible: false },
  ],
};
